source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TravisUITest_Example', :exclusive => true do
  pod "TravisUITest", :path => "../"
end

target 'TravisUITest_Tests', :exclusive => true do
  pod "TravisUITest", :path => "../"

  
end
